In [18]:
import pandas as pd

In [19]:
data = pd.read_csv("RV288U.csv")
data

,Aasta,Asustuspiirkonna liik,Mehe elukoht,Kuud kokku,Jaanuar,Veebruar,Märts,Aprill,Mai,Juuni,Juuli,August,September,Oktoober,November,Detsember
0,2017,Kokku,Kokku,3323,240,259,303,250,320,247,242,274,292,289,309,298
1,2017,Kokku,Elukoht Eestis,3147,227,244,284,236,307,233,229,261,276,270,293,287
2,2017,Kokku,Harju maakond,1569,104,117,144,112,157,118,113,139,133,128,155,149
3,2017,Kokku,..Tallinn,1145,75,84,101,81,110,82,75,102,104,94,120,117
4,2017,Kokku,Hiiu maakond,22,1,2,0,3,2,0,1,4,2,3,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,2021,Maaline asustuspiirkond,Saare maakond,35,2,0,5,0,1,4,8,5,4,3,1,2
260,2021,Maaline asustuspiirkond,Tartu maakond,73,8,1,5,1,5,7,11,14,2,9,3,7
261,2021,Maaline asustuspiirkond,Valga maakond,31,1,2,0,2,5,5,4,3,1,2,2,4
262,2021,Maaline asustuspiirkond,Viljandi maakond,47,2,5,2,5,10,6,3,4,3,3,3,1
263,2021,Maaline asustuspiirkond,Võru maakond,34,0,4,1,2,2,2,8,5,2,4,3,1

In [27]:
data_filtered = data[data['Asustuspiirkonna liik'] != "Kokku"].reset_index(drop=True)
data_filtered = data_filtered[data_filtered['Mehe elukoht'] != "Kokku"].reset_index(drop=True)
data_filtered

,Aasta,Asustuspiirkonna liik,Mehe elukoht,Kuud kokku,Jaanuar,Veebruar,Märts,Aprill,Mai,Juuni,Juuli,August,September,Oktoober,November,Detsember
0,2017,Linnaline ja väikelinnaline asustuspiirkond,Harju maakond,1398,90,106,128,100,136,104,103,123,120,107,146,135
1,2017,Linnaline ja väikelinnaline asustuspiirkond,..Tallinn,1145,75,84,101,81,110,82,75,102,104,94,120,117
2,2017,Linnaline ja väikelinnaline asustuspiirkond,Hiiu maakond,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2017,Linnaline ja väikelinnaline asustuspiirkond,Ida-Viru maakond,352,35,27,29,21,32,30,21,26,34,35,35,27
4,2017,Linnaline ja väikelinnaline asustuspiirkond,Jõgeva maakond,6,0,2,3,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2021,Maaline asustuspiirkond,Saare maakond,35,2,0,5,0,1,4,8,5,4,3,1,2
152,2021,Maaline asustuspiirkond,Tartu maakond,73,8,1,5,1,5,7,11,14,2,9,3,7
153,2021,Maaline asustuspiirkond,Valga maakond,31,1,2,0,2,5,5,4,3,1,2,2,4
154,2021,Maaline asustuspiirkond,Viljandi maakond,47,2,5,2,5,10,6,3,4,3,3,3,1
155,2021,Maaline asustuspiirkond,Võru maakond,34,0,4,1,2,2,2,8,5,2,4,3,1

In [28]:
data_filtered.to_csv("kuud_maakonnad.csv", index = False)