In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("RV35U.csv")

In [3]:
data

,Aasta,Asustuspiirkonna liik,Mehe elukoht,Kokku,0 last,1 laps,2 last,3 last,4 last,5 või enam last,Ühiste laste arv teadmata
0,2017,Kokku,Kokku,3323,1503,998,668,124,25,5,0
1,2017,Kokku,Elukoht teadmata,0,0,0,0,0,0,0,0
2,2017,Kokku,Elukoht väljaspool Eestit,176,113,33,24,5,0,1,0
3,2017,Kokku,Elukoht Eestis,3147,1390,965,644,119,25,4,0
4,2017,Kokku,Harju maakond,1569,682,494,326,58,9,0,0
...,...,...,...,...,...,...,...,...,...,...,...
310,2021,Maaline asustuspiirkond,Tartu maakond,77,25,18,27,6,0,0,1
311,2021,Maaline asustuspiirkond,Valga maakond,31,11,10,5,1,3,0,1
312,2021,Maaline asustuspiirkond,Viljandi maakond,48,21,8,11,7,0,1,0
313,2021,Maaline asustuspiirkond,Võru maakond,34,11,8,8,5,1,0,1
314,2021,Maaline asustuspiirkond,Elukoht Eestis teadmata,.,.,.,.,.,.,.,.

In [4]:
data_filtered = data[data['Asustuspiirkonna liik'] != "Kokku"].reset_index(drop=True)
data_filtered = data_filtered[data_filtered['Mehe elukoht'] != "Kokku"].reset_index(drop=True)

In [8]:
data_filtered = data_filtered[data_filtered["Mehe elukoht"].isin["Elukoht väljaspool Eestit", "Elukoht Eestis teadmata"]]

TypeError: 'method' object is not subscriptable