In [172]:
import pandas as pd

In [173]:
sots = pd.read_csv("sots.csv")
pikkus = pd.read_csv("abielu_pikkus.csv")
maakond = pd.read_csv("maakond.csv")
kuud = pd.read_csv("kuud_maakonnad.csv")

In [174]:
sots['Elukoht'] = sots['Elukoht'].str.replace('..linnaline ja väikelinnaline asustuspiirkond\xa0\xa0','Linnaline ja väikelinnaline asustuspiirkond')
sots['Elukoht'] = sots['Elukoht'].str.replace('..maaline asustuspiirkond','Maaline asustuspiirkond')

pikkus['Elukoht'] = pikkus['Elukoht'].str.replace('linnaline ja väikelinnaline asustuspiirkond','Linnaline ja väikelinnaline asustuspiirkond')
pikkus['Elukoht'] = pikkus['Elukoht'].str.replace('maaline asustuspiirkond','Maaline asustuspiirkond')

sots = sots.rename(columns={"Elukoht":"Asustuspiirkond"})
pikkus = pikkus.rename(columns={"Elukoht":"Asustuspiirkond"})
maakond = maakond.rename(columns= {"Asustuspiirkonna liik" : "Asustuspiirkond"})

C:\Users\evalotta\AppData\Local\Temp/ipykernel_2700/116479509.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  sots['Elukoht'] = sots['Elukoht'].str.replace('..linnaline ja väikelinnaline asustuspiirkond\xa0\xa0','Linnaline ja väikelinnaline asustuspiirkond')
C:\Users\evalotta\AppData\Local\Temp/ipykernel_2700/116479509.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  sots['Elukoht'] = sots['Elukoht'].str.replace('..maaline asustuspiirkond','Maaline asustuspiirkond')

In [175]:
pikkus2017 = pikkus.query("Aasta == 2017 & Sugu == 'Mehed'")
pikkus2017 = pikkus2017.drop(columns=["Sugu", "Aasta"])

sots2017 = sots.query("Sugu == 'Mehed'")
sots2017 = sots2017.drop(columns=["Sugu", "Aasta"])

In [176]:
kokku = sots2017.merge(pikkus2017, on=["Asustuspiirkond", "Vanuserühm", "Kokku"])

maaline = kokku.query("Asustuspiirkond == 'Maaline asustuspiirkond'")
linnaline = kokku.query("Asustuspiirkond == 'Linnaline ja väikelinnaline asustuspiirkond'")

In [177]:
maaline

,Asustuspiirkond,Vanuserühm,Kokku,Töötav,Töötu,Pensionär,(Üli)õpilane,Töövõimetu*,Kodune,Kinnipeetav*,...,4 aastat,5 aastat,6 aastat,7 aastat,8 aastat,9 aastat,10-14 aastat,15-19 aastat,20 ja enam aastat,Abielu kestus teadmata
13,Maaline asustuspiirkond,15-19,0,0,0,0,0,..,0,..,...,0,0,0,0,0,0,0,0,0,0
14,Maaline asustuspiirkond,20-24,6,2,0,0,0,..,0,..,...,0,0,0,0,0,0,0,0,0,0
15,Maaline asustuspiirkond,25-29,53,8,1,0,0,..,0,..,...,6,5,3,0,1,2,2,0,0,0
16,Maaline asustuspiirkond,30-34,116,14,7,0,1,..,0,..,...,8,14,12,13,10,7,11,0,0,0
17,Maaline asustuspiirkond,35-39,114,8,5,0,0,..,1,..,...,5,11,11,7,3,8,34,11,0,0
18,Maaline asustuspiirkond,40-44,145,16,3,0,0,..,1,..,...,10,7,6,5,5,5,35,34,22,0
19,Maaline asustuspiirkond,45-49,147,11,4,4,0,..,0,..,...,5,1,4,3,3,2,27,34,56,0
20,Maaline asustuspiirkond,50-54,105,14,5,1,0,..,0,..,...,0,3,1,2,2,2,4,10,76,0
21,Maaline asustuspiirkond,55-59,86,18,4,7,0,..,0,..,...,0,3,0,2,1,1,2,7,66,0
22,Maaline asustuspiirkond,60-64,45,4,0,12,0,..,0,..,...,2,0,0,2,1,1,1,3,35,0
23,Maaline asustuspiirkond,65-69,27,2,0,10,0,..,0,..,...,0,0,0,0,0,0,1,2,21,1
24,Maaline asustuspiirkond,70-74,11,0,0,3,0,..,0,..,...,0,0,0,0,0,1,1,4,5,0
25,Maaline asustuspiirkond,75 ja vanemad,8,0,0,3,0,..,0,..,...,0,0,0,0,0,0,0,1,6,1

In [179]:
maakond['Mehe elukoht'].value_counts()

Põlva maakond         10
Viljandi maakond      10
Ida-Viru maakond      10
Jõgeva maakond        10
Järva maakond         10
Lääne maakond         10
Lääne-Viru maakond    10
Võru maakond          10
Pärnu maakond         10
Rapla maakond         10
Saare maakond         10
Tartu maakond         10
Valga maakond         10
Hiiu maakond           9
Harju maakond          5
Tallinn                4
Kokku                  1
Name: Mehe elukoht, dtype: int64

In [ ]:
maakond['Mehe elukoht'] = maakond['Mehe elukoht'].str.replace('Harju maakond','Harju maakond (v.a Tallinn)')
kuud['Mehe elukoht'] = kuud['Mehe elukoht'].str.replace('Harju maakond','Harju maakond (v.a Tallinn)')
maakond = maakond.rename(columns={"Mehe elukoht":"Elukoht"})
kuud = kuud.rename(columns={"Mehe elukoht":"Elukoht"})

Tahtsin muidu mergida dataframe'd maakond ja kuud, aga praegu on maakond tabelist mingid maakonnad puudu (vt value_counts() üleval). See tuleb korda saada enne kui saab edasi minna.